CREATE TAble IF NOT EXISTS users(
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULl,
    password VARCHAR(255) NOT NULL,
    age TINYINT(3) UNSIGNED NOT NULL,
    country VARCHAR(255) NOT NULL,
    socila_media_url VARCHAR(255) NOT NULl,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY(id),
    UNIQUE KEY(email)
);
CREATE TAble IF NOT EXISTS transactions(
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    description VARCHAR(255) NOT NULl,
    amount DECIMAL(10,2) NOT NULL,
    date DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    user_id BIGINT(20) UNSIGNED NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS receipts(
  id BIGINT(20) unsigned NOT NULL AUTO_INCREMENT,
  original_filename VARCHAR(255) NOT NULL,
  storage_filename VARCHAR(255) NOT NULL,
  media_type VARCHAR(255) NOT NULL,
  transaction_id BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY(transaction_id) REFERENCES transactions (id) ON DELETE CASCADE
);
