CREATE TAble IF NOT EXISTS users(
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULl,
    password VARCHAR(255) NOT NULL,
    age TINYINT(3) UNSIGNED NOT NULL,
    country VARCHAR(255) NOT NULL,
    socila_media_url VARCHAR(255) NOT NULl,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY(id),
    UNIQUE KEY(email)
);